// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2rOAxjlX19kOWplmQOpuW7rcasEOR6Wg',
    appId: '1:343221001297:web:8fbd8659a90e6fb53f6c70',
    messagingSenderId: '343221001297',
    projectId: 'chat-app-843a2',
    authDomain: 'chat-app-843a2.firebaseapp.com',
    storageBucket: 'chat-app-843a2.appspot.com',
    measurementId: 'G-6C6P4B44Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqlwVO1jF8qmGafllOl3A0raQNdcfrFM',
    appId: '1:343221001297:android:bd4e662d10046fc73f6c70',
    messagingSenderId: '343221001297',
    projectId: 'chat-app-843a2',
    storageBucket: 'chat-app-843a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVzBrAU1QkfTQWNcQO8jfq73NNjQl7ZB0',
    appId: '1:343221001297:ios:5ae0ba312b7689923f6c70',
    messagingSenderId: '343221001297',
    projectId: 'chat-app-843a2',
    storageBucket: 'chat-app-843a2.appspot.com',
    iosClientId: '343221001297-u5414opudklk0nfm8vjt84fjtj095s2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVzBrAU1QkfTQWNcQO8jfq73NNjQl7ZB0',
    appId: '1:343221001297:ios:5ae0ba312b7689923f6c70',
    messagingSenderId: '343221001297',
    projectId: 'chat-app-843a2',
    storageBucket: 'chat-app-843a2.appspot.com',
    iosClientId: '343221001297-u5414opudklk0nfm8vjt84fjtj095s2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
